#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

push @INC, join('/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib');

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'WorkOut';

# Start commands
my $cmd = Mojolicious::Commands->new;

# Add WorkOut::Command namespace for additional commands
my $ns = $cmd->namespaces;
push @$ns, 'WorkOut::Command';
$cmd->namespaces($ns);

$cmd->start;
